# GitHub Pages Configuration - SIMPLIFICADO
title: "Cuenta de Cajas - PWA de Conteo"
description: "Aplicación web progresiva moderna para el conteo eficiente de cajas y palets con edición de cantidades y contraste mejorado para mejor accesibilidad"

# Build settings - MÍNIMO
markdown: kramdown

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - backup_app_conteo/
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

# Include files
include:
  - _headers
  - _redirects

# PWA Settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# SEO
lang: es
author: "Desarrollador PWA"
twitter:
  username: tu-usuario
  card: summary_large_image

social:
  name: "Aplicación PWA de Conteo"
  links:
    - "https://github.com/tu-usuario/nombre-repositorio"

# Analytics (opcional)
# google_analytics: UA-XXXXXXXX-X