# GitHub Pages Configuration - SIMPLIFICADO
title: "App Conteo de Cajas"
description: "Aplicación PWA para conteo de cajas con teclado numérico profesional, gestión de bloques, visibilidad optimizada del texto y edición mejorada de cantidades"
url: "https://elmijanocm-rgb.github.io"
baseurl: "/cuenta-de-cajas"

# Build settings - MÍNIMO
markdown: kramdown

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - backup_app_conteo/
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

# Include files
include:
  - _headers
  - _redirects

# PWA Settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# SEO
lang: es
author: "Desarrollador PWA"
twitter:
  username: tu-usuario
  card: summary_large_image

social:
  name: "Aplicación PWA de Conteo"
  links:
    - "https://github.com/tu-usuario/nombre-repositorio"

# Analytics (opcional)
# google_analytics: UA-XXXXXXXX-X